version: 2.1
orbs:
  codecov: codecov/codecov@1

jobs:
  working_directory: src
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Use mvn clean and package as the standard maven build phase
      - run:
          name: test-package
          command: mvn clean package
      - codecov/upload
      
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  myflow:  
    jobs:
      - build-and-test
       
