/*DROP table BEECP_TEST;*/
CREATE TABLE BEECP_TEST( 
  TEST_ID VARCHAR(50), 
  TEST_NAME VARCHAR(50)  
);	 

/*DROP PROCEDURE BEECP_HELLO;*/
DELIMITER $$
CREATE PROCEDURE BEECP_HELLO()
BEGIN
   SELECT 'hello';
END$$